config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from main import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index),
    path("switch-read/", views.switch_read),
    path("switch-write/", views.switch_write),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import datetime
import uuid

from django.db import models
from django.utils import timezone


class Link(models.Model):
    active = models.BooleanField(default=None)
    icon = models.ImageField()
    name = models.CharField(max_length=127)
    url = models.URLField()


class WordOfTheDay(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date = models.DateField(default=datetime.date.today)
    word = models.CharField(max_length=127)


class Definition(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    word = models.ForeignKey(WordOfTheDay, on_delete=models.CASCADE)
    part_of_speech = models.CharField(max_length=31)
    definition = models.TextField()


class Example(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    word = models.ForeignKey(WordOfTheDay, on_delete=models.CASCADE)
    example = models.TextField()


class Prompt(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    prompt = models.CharField(max_length=255)
    selected_date = models.DateField(null=True, blank=True)


class Entry(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    prompt = models.ForeignKey(Prompt, on_delete=models.SET_NULL, null=True)
    text = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now)
    wordcount = models.PositiveSmallIntegerField()

    def save(self, *args, **kwargs):
        self.wordcount = len(self.text.split(" "))
        super().save(*args, **kwargs)

main/views.py
import datetime
import json
import random
import requests

from django import http
from django.conf import settings
from django.shortcuts import render

from main import models


def _get_daily_prompt():
    today = datetime.date.today()
    try:
        prompt = models.Prompt.objects.get(selected_date=today)
    except models.Prompt.DoesNotExist:
        prompt = random.choice(models.Prompt.objects.all())
        prompt.selected_date = today
        prompt.save()
    return prompt


def _get_wotd():
    today = datetime.date.today()
    api_key = settings.WORDNIK_SECRET
    api_url = f"https://api.wordnik.com/v4/words.json/wordOfTheDay?date={today}&api_key={api_key}"
    try:
        wotd = models.WordOfTheDay.objects.get(date=today)
    except models.WordOfTheDay.DoesNotExist:
        response = requests.get(api_url).json()
        wotd = models.WordOfTheDay.objects.create(word=response["word"])
        for definition in response["definitions"]:
            models.Definition.objects.create(
                word=wotd,
                part_of_speech=definition["partOfSpeech"],
                definition=definition["text"],
            )
        for example in response["examples"]:
            models.Example.objects.create(
                word=wotd,
                example=example["text"],
            )
    return wotd


def index(request):
    if request.is_ajax():
        prompt = models.Prompt.objects.get(prompt=request.POST["prompt"])
        entry = request.POST["entry"]
        secret = request.POST["secret"]
        if secret == settings.FORM_SECRET:
            models.Entry.objects.create(
                prompt=prompt,
                text=entry,
            )
            return http.JsonResponse({"status": 200})
        return http.JsonResponse({"status": 401})
    links = models.Link.objects.filter(active=True)
    prompt = _get_daily_prompt()
    wotd = _get_wotd()
    return render(
        request, "base.html", {"links": links, "prompt": prompt, "wotd": wotd}
    )


def switch_read(request):
    entry = random.choice(models.Entry.objects.all())
    return http.JsonResponse(
        {
            "status": 200,
            "prompt": entry.prompt.prompt,
            "text": entry.text,
            "words": str(entry.wordcount),
        }
    )


def switch_write(request):
    return http.JsonResponse({"status": 200, "prompt": _get_daily_prompt().prompt})

main/templates/base.html
{% load static %}
{% load sass_tags %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <title>Welcome</title>

    <link rel="canonical" href="https://{{ request.get_host }}{{ request.get_full_path }}" />
    <link rel="stylesheet" href="{% sass_src 'css/base.scss' %}" type="text/css" />
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container--left">
      <section class="heading">
        <h2 class="heading__datetime">{% now 'F jS, Y' %}</h2>
        <p id="time" class="heading__datetime"></p>
      </section>
      <section class="links">
        {% for link in links %}
          <a class="link" href="{{ link.url }}">
            <img class="link__image" src="{{ link.icon.url }}" /> {{ link.name }}
          </a>
        {% endfor %}
      </section>
      <section class="switches">
        <button type="button" class="switch switch--write" onclick="switchWrite();">Write</button>
        <button type="button" class="switch switch--read" onclick="switchRead();">Read</button>
      </section>
    </div>
    <div class="container--right">
      <section class="writing">
        <p class="writing__prompt">{{ prompt.prompt }}</p>
        <div class="writing__form">
          <div class="writing__form--fade"></div>
          <textarea class="writing__form--textarea" onkeyup="getWordCount(this);" autofocus></textarea>
        </div>
        <div class="writing__end">
          <form id="submission-form">
            <input class="writing__secret" type="password" />
            <input class="writing__submit" type="submit" value="›" />
          </form>
          <p id="wordcount" class="writing__wordcount"></p>
        </div>
      </section>
      <section class="wotd">
        <h2 class="wotd__word">{{ wotd.word }}</h2>
        <h5 class="wotd__header">Definitions</h5>
        {% for definition in wotd.definition_set.all %}
          <p class="wotd__subhead">{{ forloop.counter }}. ({{ definition.part_of_speech }})</p>
          <p class="wotd__definition">{{ definition.definition }}</p>
        {% endfor %}
        <h5 class="wotd__header">Examples</h5>
        {% for example in wotd.example_set.all %}
          <p class="wotd__example">"{{ example.example }}"</p>
        {% endfor %}
      </section>
    </div>
  </body>
  <script>
    /* display time */
    var timeElement = document.getElementById("time");

    window.setInterval(function() {
      var d = new Date();
      var hr = d.getHours();
      var min = d.getMinutes();
      var ampm = "a.m.";

      if (min < 10) { min = "0" + min; }
      if (hr > 12) {
        hr -= 12;
        ampm = "p.m.";
      }

      timeElement.innerHTML = `${hr}:${min} ${ampm}`;
    }, 500);
  </script>
  <script>
    /* display wordcount */
    var wordCountElement = document.getElementById("wordcount");

    function getWordCount(element) {
      var wordCount = element.value.split(" ").length;
      wordCountElement.innerText = wordCount;
    }
  </script>
  <script>
    /* form submission */
    $("#submission-form").submit(function(e) {
      e.preventDefault();
      /* TODO: instantiate secret, prompt & entry */
      var prompt = $(".writing__prompt")[0].innerText;
      var entry = $(".writing__form--textarea")[0].value;
      var secret = $(".writing__secret")[0].value;

      $.ajax({
        type: "POST",
        url: "/",
        headers: { "X-CSRFToken": "{{ csrf_token }}" },
        data: {
          secret: secret,
          prompt: prompt,
          entry: entry,
        },
        success: function(data) {
          console.log(data);
        },
        error: function(data) {
          console.log(data);
        },
      });
    });
  </script>
  <script>
    /* handle read/write switch */
    function switchRead() {
      var prompt = $(".writing__prompt")[0];
      var textarea = $(".writing__form--textarea")[0];
      var wordCountElement = $("#wordcount")[0];
      var submissionForm = $("#submission-form")[0];

      $.ajax({
        type: "GET",
        url: "/switch-read/",
        success: function(data) {
          /* update prompt, textarea, and wordcount */
          prompt.innerText = data.prompt;
          textarea.innerText = data.text;
          $(".writing__form--textarea").prop("readonly", true);
          wordCountElement.innerText = data.words;
          submissionForm.style.display = "none";
        },
        error: function(data) {
          console.log(data);
        }
      });
    }

    function switchWrite() {
      var prompt = $(".writing__prompt")[0];
      var textarea = $(".writing__form--textarea")[0];
      var wordCountElement = $("#wordcount")[0];
      var submissionForm = $("#submission-form")[0];

      $.ajax({
        type: "GET",
        url: "/switch-write/",
        success: function(data) {
          /* reset prompt, textarea, and wordcount */
          prompt.innerText = data.prompt;
          textarea.innerText = "";
          $(".writing__form--textarea").prop("readonly", false);
          $(".writing__form--textarea").focus();
          wordCountElement.innerText = "0";
          submissionForm.style.display = "initial";
        },
        error: function(data) {
          console.log(data);
        }
      });
    }
  </script>
</html>